version: 0.2
env: 
  variables:
    key=value
phases:

  pre_build:
    commands:
      - aws --version
      - npm install --silent
      - npm install react-scripts@3.4.1 -g --silent
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
  build:
    commands:
      - echo Build started on `date`
      - npm run build 
      -
          if [ "$CODEBUILD_WEBHOOK_HEAD_REF" == "refs/heads/dev" ]; then
            aws s3 sync "./build" s3://terraforms3bucket1234/dev
          fi
      - 

