version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t react-app .
      - docker run --env AWS_DEFAULT_REGION=us-east-1 react-app