version: 0.2

phases:

  pre_build:
    commands:
      - aws --version
      - npm install --silent
      - npm install react-scripts@3.4.1 -g --silent
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      - aws s3 sync "./build" s3://$S3_BUCKET/$CODEBUILD_GIT_BRANCH
